#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 17 15:35:37 2021

@author: ali
"""

import cv2
import os

path = "/home/ali/YOLOV5/assets/Taipei.mp4"
vidcap = cv2.VideoCapture(path)
skip_frame = 10

def Analysis_path(path):
    file = path.split("/")[-1]
    file_name = file.split(".")[0]
    file_dir = os.path.dirname(path)
    return file,file_name,file_dir

success,image = vidcap.read()
count = 0
file,filename,file_dir = Analysis_path(path)
print(file," ",filename," ",file_dir)
save_folder_name =  filename + "_imgs"
save_dir = os.path.join(file_dir,save_folder_name)
if not os.path.exists(save_dir):
    os.makedirs(save_dir)

while success:
    if count%skip_frame==0:
        
        filename_ = filename + "_" + str(count) + ".jpg"
        img_path = os.path.join(save_dir,filename_)
        
        cv2.imwrite(img_path,image)
        #cv2.imwrite("/home/ali/datasets-old/TL4/frame%d.jpg" % count, image)     # save frame as JPEG file    
        print('save frame ',count)
    success,image = vidcap.read()
    print('Read a new frame: ', success)
    count += 1
